### PR TITLE
Fix initializer running multiple times in tests

### LINKED ISSUE #5: Self-recursing filterBy
This addon uses an [initializer](https://github.com/ember-data/ember-data-live-filter-by/blob/master/addon/initializers/live-filter.js) to overwrite the built-in `filterBy`:
```
DS.RecordArray.reopen({ filterBy: liveFilterBy });
```

`liveFilterBy` adds some extra logic then calls [_super](https://github.com/ember-data/ember-data-live-filter-by/blob/master/addon/live-filter-by.js#L12) (the default `filterBy`). Except, well, the initializer runs before every test so after N tests you will have N recursive calls to `liveFilterBy` followed by 1 call to `filterBy`. Eventually you might hit the browser recursion limit if you have enough tests:

```
too much recursion
liveFailterBy@http://localhost:4201/assets/vendor.js:394787:12
superWrapper@http://localhost:4201/assets/vendor.js:68434:17
liveFailterBy@http://localhost:4201/assets/vendor.js:394787:12
superWrapper@http://localhost:4201/assets/vendor.js:68434:17
liveFailterBy@http://localhost:4201/assets/vendor.js:394787:12
superWrapper@http://localhost:4201/assets/vendor.js:68434:17
liveFailterBy@http://localhost:4201/assets/vendor.js:394787:12
superWrapper@http://localhost:4201/assets/vendor.js:68434:17
liveFailterBy@http://localhost:4201/assets/vendor.js:394787:12
<snip>
```

### PR DESCRIPTION
**Pull request by dwickern**
Fixes #5

### CODE REVIEW

**Comment by runspired** [comment]
No authority to merge but 👌

I think @bmac can?

**Comment by bmac** [comment]
Thanks @dwickern.

**Comment by dwickern** [comment]
@bmac could you publish a build?

**Comment by dwickern** [comment]
Ping, still waiting on a release :)

**Comment by bmac** [comment]
Thanks @dwickern. I missed your earlier ping. I just published 1.1.0 to npm.

**Pull request merged**
